JobFly/Models/Vacancy.cs
using static System.Net.Mime.MediaTypeNames;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace JobFly.Models
{
    public class Vacancy
    {
        [Key]
        public int Id { get; set; }
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Task Description is required")]
        public string TaskDescription { get; set; }

        [Required(ErrorMessage = "Must to have is required")]
        public string MustToHave { get; set; }

        [Required(ErrorMessage = "Must to have is required")]
        public string GoodToHave { get; set; }

        [Required(ErrorMessage = "Salary is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Salary must be greater than 0")]
        public int Salary { get; set; }
        public bool IsActive { get; set; } 

        [ForeignKey("Employer")]
        public string EmployerId { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<VacancyTag> VacancyTags { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
    }
}

JobFly/Areas/Admin/Controllers/VacancyController.cs
using JobFly.Areas.Employer.Models;
using JobFly.Areas.Employer.Services;
using JobFly.Data;
using JobFly.Models;
using JobFly.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace JobFly.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "AdminOnly")]
    public class VacancyController : Controller
    {
        private readonly IVacancyService _vacancyService;
        private readonly ICategoryService _categoryService;
        private const int PageSize = 10;

        public VacancyController(IVacancyService vacancyService, ICategoryService categoryService)
        {
            _vacancyService = vacancyService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(string title, int? categoryId, int page = 1, ViewModels.VacancySortState sortOrder = VacancySortState.IdAsc)
        {
            var vacancies = await _vacancyService.GetVacancies(title, categoryId, sortOrder, page, PageSize);
            var count = await _vacancyService.GetVacanciesCount(title, categoryId);
            var categories = await _categoryService.GetAll();

            var viewModel = new VacancyIndexViewModel(
                vacancies,
                new PageViewModel(count, page, PageSize),
                new FilterViewModel(title, categories, categoryId),
                new VacancySortViewModel(sortOrder),
                categories
            );


            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                await _vacancyService.Delete(id);
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

JobFly/Areas/Employee/Controllers/VacancyController.cs
using JobFly.Areas.Employer.Models;
using JobFly.Areas.Employer.Services;
using JobFly.Models;
using JobFly.Services;
using JobFly.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JobFly.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize(Policy = "EmployeeOnly")]
    public class VacancyController : Controller
    {
        private readonly IVacancyService _vacancyService;
        private readonly ICategoryService _categoryService;
        private readonly IApplicationService _applicationService;
        private const int PageSize = 10;
        public VacancyController(IVacancyService vacancyService, ICategoryService categoryService, IApplicationService applicationService)
        {
            _vacancyService = vacancyService;
            _categoryService = categoryService;
            _applicationService = applicationService;
        }
        public async Task<IActionResult> Index(string title, int? categoryId, int page = 1, VacancySortState sortOrder = VacancySortState.IdAsc)
        {
            var vacancies = await _vacancyService.GetVacancies(title, categoryId, sortOrder, page, PageSize);
            var count = await _vacancyService.GetVacanciesCount(title, categoryId);
            var categories = await _categoryService.GetAll();

            var viewModel = new VacancyIndexViewModel(
                vacancies,
                new PageViewModel(count, page, PageSize),
                new FilterViewModel(title, categories, categoryId),
                new VacancySortViewModel(sortOrder),
                categories
            );

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Details(int vacancyId)
        {
            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return Unauthorized("Користувач не авторизований.");
            }


            var application = new Application
            {
                VacancyId = vacancyId,
                EmployeeId = userId,
                Status = "Not readed",
                DateApplied = DateTime.Now
            };

            await _applicationService.Create(application);

            return RedirectToAction("Index");
        }


    }
}

JobFly/Areas/Employer/Controllers/VacancyController.cs
using JobFly.Areas.Employer.Models;
using JobFly.Areas.Employer.Services;
using JobFly.Data;
using JobFly.Models;

using JobFly.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace JobFly.Areas.Employer.Controllers
{
    [Area("Employer")]
    [Authorize(Policy = "EmployerOnly")]
    public class VacancyController : Controller
    {
        private readonly IVacancyService _vacancyService;
        private readonly ICategoryService _categoryService;
        //private readonly IApplicationService _applicationService;
        private const int PageSize = 10;

        public VacancyController(IVacancyService vacancyService, ICategoryService categoryService)
        {
            _vacancyService = vacancyService;
            _categoryService = categoryService;
            //_applicationService = applicationService;
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var categories = await _categoryService.GetAll();
            var viewModel = new VacancyCreateViewModel
            {
                Categories = categories
            };
            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(VacancyCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = await _categoryService.GetAll();
                return View(model);
            }

            var vacancy = new Vacancy
            {
                Title = model.Title,
                TaskDescription = model.TaskDescription,
                MustToHave = model.MustToHave,
                GoodToHave = model.GoodToHave,
                Salary = model.Salary,
                CategoryId = model.CategoryId.Value,
                IsActive = true,
                EmployerId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value
            };

            await _vacancyService.Create(vacancy);

            return RedirectToAction("Index");
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                await _vacancyService.Delete(id);
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();

            var vacancy = await _vacancyService.GetVacancyById(id.Value);
            if (vacancy == null)
                return NotFound();

            // Мапимо Vacancy в ViewModel
            var viewModel = new VacancyUpdateViewModel
            {
                Id = vacancy.Id,
                Title = vacancy.Title,
                TaskDescription = vacancy.TaskDescription,
                MustToHave = vacancy.MustToHave,
                GoodToHave = vacancy.GoodToHave,
                Salary = vacancy.Salary,
                IsActive = vacancy.IsActive
            };

            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            if (id != null)
            {
                //var vacancy = await _vacancyService.GetVacancyById(id.Value);
                var applications = await _vacancyService.GetApplicationsForVacancy(id);
                return View(applications);

            }
            return NotFound();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Update(VacancyUpdateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var existingVacancy = await _vacancyService.GetVacancyById(model.Id);
            if (existingVacancy == null)
                return NotFound();

            // Оновлюємо поля
            existingVacancy.Title = model.Title;
            existingVacancy.TaskDescription = model.TaskDescription;
            existingVacancy.MustToHave = model.MustToHave;
            existingVacancy.GoodToHave = model.GoodToHave;
            existingVacancy.Salary = model.Salary;
            existingVacancy.IsActive = model.IsActive;

            await _vacancyService.Update(existingVacancy);

            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> Index(string title, int page = 1, int? categoryId = null,
    ViewModels.VacancySortState sortOrder = VacancySortState.IdAsc)
        {
            var employerId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            var vacancies = await _vacancyService.GetVacanciesForEmployer(employerId, title, categoryId, sortOrder, page, PageSize);
            var count = await _vacancyService.GetVacanciesCountForEmployer(employerId, title, categoryId);

            // Отримуємо список всіх категорій
            var categories = await _categoryService.GetAll();

            VacancyIndexViewModel viewModel = new VacancyIndexViewModel(
                vacancies,
                new PageViewModel(count, page, PageSize),
                new FilterViewModel(title, categories, categoryId),
                new VacancySortViewModel(sortOrder),
                categories

            );

            return View(viewModel);
        }


    }
}

JobFly/Areas/Employer/Views/Vacancy/Create.cshtml
@model JobFly.Areas.Employer.Models.VacancyCreateViewModel

<h2>Create a vacancy</h2>
<form asp-action="Create" asp-controller="Vacancy" method="post">
    <p>
        <label asp-for="Title">Title</label><br />
        <input type="text" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="TaskDescription">Task Description</label><br />
        <textarea asp-for="TaskDescription" class="form-control" placeholder="Enter what tasks your potential employee will solve, what he will encounter during the work process"></textarea>
        <span asp-validation-for="TaskDescription" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="MustToHave">Must to have</label><br />
        <textarea asp-for="MustToHave" class="form-control" placeholder="Enter what obligatory skills your potential employee must to have"></textarea>
        <span asp-validation-for="MustToHave" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="GoodToHave">Good to have</label><br />
        <textarea asp-for="GoodToHave" class="form-control" placeholder="Enter what desirable skills your potential employee should have"></textarea>
        <span asp-validation-for="GoodToHave" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="Salary">Salary</label><br />
        <input type="number" asp-for="Salary" />
        <span asp-validation-for="Salary" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="CategoryId">Category</label><br />
        <select asp-for="CategoryId" asp-items="@(new SelectList(Model.Categories, "Id", "Title"))">
            <option value="">-- Select Category --</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </p>
    <p>
        <input type="submit" value="Create" class="btn btn-primary" />
    </p>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

JobFly/Areas/Employer/Views/Vacancy/Details.cshtml
@using JobFly.Models

<h1>Applications for Vacancy</h1>

@if (Model == null)
{
    <p>No applications found for this vacancy.</p>
}
else
{
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Resume</th>
            <th>Date</th>
        </tr>
        @foreach (var application in Model)
        {
            <tr>
                <td>@application.Employee?.User.Name</td>
                <td>@application.Employee?.User.Surname</td>
                <td>@application.Employee?.User.Email</td>
                <td>@application.Employee?.User.PhoneNumber</td>
                <td>@application.Employee?.ResumeText</td>
                <th>@application.DateApplied</th>
            </tr>
        }
    </table>
}

JobFly/Areas/Employer/Views/Vacancy/Index.cshtml
@using JobFly.Models

<style>
    .glyphicon {
        display: inline-block;
        padding: 0 5px;
    }

    .glyphicon-chevron-right:after {
        content: "\00BB";
    }

    .glyphicon-chevron-left:before {
        content: "\00AB";
    }
</style>


<h1>Your Vacancies</h1>

<form method="get">
    <label>Title: </label>
    <input name="title" value="@Model.FilterViewModel.SelectedTitle" />

    <label>Category: </label>
    <select name="categoryId">
        <option value="">All</option>
        @foreach (var category in Model.FilterViewModel.Categories)
        {
            <option value="@category.Id" selected="@(category.Id == Model.FilterViewModel.SelectedCategoryId)">
                @category.Title
            </option>
        }
    </select>

    <input type="submit" value="Filter" />
</form>

<table>
    <tr>
        <th><a asp-action="Index" asp-route-sortOrder="@(Model.VacancySortViewModel.IDSort)" asp-route-title="@Model.FilterViewModel.SelectedTitle">ID</a></th>
        <th><a asp-action="Index" asp-route-sortOrder="@(Model.VacancySortViewModel.TitleSort)" asp-route-title="@Model.FilterViewModel.SelectedTitle">Title</a></th>
        <th>Task Description</th>
        <th>Must to have</th>
        <th>Good to have</th>
        <th><a asp-action="Index" asp-route-sortOrder="@(Model.VacancySortViewModel.SalarySort)" asp-route-title="@Model.FilterViewModel.SelectedTitle">Salary</a></th>
        <th>
            <a asp-action="Index" asp-route-sortOrder="@(Model.VacancySortViewModel.StatusSort)"
               asp-route-title="@(Model.FilterViewModel.SelectedTitle)">Is active</a>
        </th>
        <th>Category</th>      
    </tr>
    @foreach (var vacancy in Model.Vacancies)
    {
        <tr>
            <td>@vacancy.Id</td>
            <td>@vacancy.Title</td>
            <td>@vacancy.TaskDescription</td>
            <td>@vacancy.MustToHave</td>
            <td>@vacancy.GoodToHave</td>
            <td>@vacancy.Salary</td>
            <td>@vacancy.IsActive</td>
            <td>@vacancy.Category?.Title</td>
            
            <td>
                <a asp-action="Details" asp-route-id="@vacancy.Id">Details</a>
            </td>
            <td>
                <a asp-action="Update" asp-route-id="@vacancy.Id">Edit</a> 
            </td>
            <td>
                <form asp-controller="Vacancy" asp-action="Delete" method="post" asp-route-id="@vacancy.Id">
                    <input type="submit" value="Delete" />
                </form>
            </td>
        </tr>
    }
</table>

<p>
    @if (Model.PageViewModel.HasPreviousPage)
    {
        <a asp-action="Index"
           asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
           asp-route-title="@Model.FilterViewModel.SelectedTitle"
           asp-route-sortorder="@Model.VacancySortViewModel.Current">Back</a>
    }
    @if (Model.PageViewModel.HasNextPage)
    {
        <a asp-action="Index"
           asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
           asp-route-title="@Model.FilterViewModel.SelectedTitle"
           asp-route-sortorder="@Model.VacancySortViewModel.Current">Next</a>
    }
</p>

JobFly/Areas/Employer/Views/Vacancy/Update.cshtml
@model JobFly.Areas.Employer.Models.VacancyUpdateViewModel

<h2>Edit vacancy</h2>

<form asp-action="Update" asp-controller="Vacancy" asp-route-id="@Model.Id">
   
    <p>
        <label asp-for="Title"></label><br />
        <input type="text" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="TaskDescription"></label><br />
        <input type="text" asp-for="TaskDescription" />
        <span asp-validation-for="TaskDescription" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="MustToHave"></label><br />
        <input type="text" asp-for="MustToHave" />
        <span asp-validation-for="MustToHave" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="GoodToHave"></label><br />
        <input type="text" asp-for="GoodToHave"/>
        <span asp-validation-for="GoodToHave" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="Salary"></label><br />
        <input type="number" asp-for="Salary"/>
        <span asp-validation-for="Salary" class="text-danger"></span>
    </p>
    <p>
        <label asp-for="IsActive">Active</label><br />
        <input type="checkbox" asp-for="IsActive" />
        <span asp-validation-for="IsActive" class="text-danger"></span>
    </p>
    <p>
        <input type="submit" value="Submit" class="btn btn-primary" />
    </p>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

JobFly/Areas/Employer/Views/Vacancy/VacancySortListModel.cshtml
@model JobFly.ViewModels.VacancyListViewModel
<form method="get">
    <div>
        <label>Назва проекту: </label>
        <input asp-for="Title" />

        <input type="submit" value="Фільтр" />
    </div>
</form>